---
site_name: Fraymakers API Docs
site_url: https://shifterbit.github.io/fraymakers-api-docs/
repo_url: https://github.com/shifterbit/fraymakers-api-docs/
repo_name: shifterbit/fraymakers-api-docs
site_description: "Unofficial Searchable Documentation for the Fraymakers API"
dev_addr: "0.0.0.0:8000"
use_directory_urls: true
markdown_extensions:
  - smarty
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - sane_lists
docs_dir: "./docs"

plugins:
  - offline
  - social:
      cache: false
  - awesome-pages
  - privacy
  - search:
      min_search_length: 3
      indexing: "full"
      separator: '[\s\-, :!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.pruning
    - navigation.expand
    - search.highlight
    - search.suggest
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.instant

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
