site_name: Fraymakers API Docs  
site_url: https://shifterbit.github.io/fraymakers-api-docs/
markdown_extensions:
  - smarty
  - pymdownx.highlight:
      use_pygments: false
      linenums: true
  - toc:
      permalink: true
  - sane_lists
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - js/highlight.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
docs_dir: "./docs"
plugins: 
  - offline
  - search:
      min_search_length: 3
      indexing: "full"
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - toc.follow
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.suggest
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.instant

  palette: 
      # Palette toggle for light mode
      - scheme: default
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode


